pull_request_rules:  
  - name: automatic merge for pull request based on label and ci success
    conditions:
      - label~=LGTM$
      - check-success=continuous-integration/appveyor/pr
    actions:
      merge:
        method: squash
  - name: automatic merge for Dependabot pull requests based on ci success
    conditions:
      - author=dependabot[bot]
      - check-success=continuous-integration/appveyor/pr
    actions:
      merge:
        method: squash
  - name: automatic merge for Transifex pull requests based on ci success
    conditions:
      - author=transifex-integration[bot]
      - check-success=continuous-integration/appveyor/pr
    actions:
      merge:
        method: squash
  - name: automatic merge for ImgBot pull requests based on ci success
    conditions:
      - author=imgbot[bot]
      - check-success=continuous-integration/appveyor/pr
    actions:
      merge:
        method: squash
  - name: assign next-release milestone to automated pull requests
    conditions:
      - author~=^(dependabot|transifex-integration|imgbot)\[bot\]$
      - milestone!=next-release
    actions:
      milestone:
        title: next-release
