//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETworkManager.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETworkManager.Localization.Resources.StaticStrings", typeof(StaticStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV ähnelt.
        /// </summary>
        public static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 9600 ähnelt.
        /// </summary>
        public static string ExampleBaud9600 {
            get {
                return ResourceManager.GetString("ExampleBaud9600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows-Testuser ähnelt.
        /// </summary>
        public static string ExampleCredentialName {
            get {
                return ResourceManager.GetString("ExampleCredentialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://$$HOSTNAME$$/ ähnelt.
        /// </summary>
        public static string ExampleCustomCommandVariableHostname {
            get {
                return ResourceManager.GetString("ExampleCustomCommandVariableHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die example.com ähnelt.
        /// </summary>
        public static string ExampleDomain {
            get {
                return ResourceManager.GetString("ExampleDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Servers ähnelt.
        /// </summary>
        public static string ExampleGroupServers {
            get {
                return ResourceManager.GetString("ExampleGroupServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switche ähnelt.
        /// </summary>
        public static string ExampleGroupSwitche {
            get {
                return ResourceManager.GetString("ExampleGroupSwitche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SERVER-01 ähnelt.
        /// </summary>
        public static string ExampleHostname {
            get {
                return ResourceManager.GetString("ExampleHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.178.1; example.com ähnelt.
        /// </summary>
        public static string ExampleHostnameAndOrIPAddress {
            get {
                return ResourceManager.GetString("ExampleHostnameAndOrIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SERVER-01 or 172.16.0.100 ähnelt.
        /// </summary>
        public static string ExampleHostnameOrIPAddress {
            get {
                return ResourceManager.GetString("ExampleHostnameOrIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.1.0/24; 192.168.178.1 - 192.168.178.128; 192.168.[178-179].[1,100,150-200]; example.com/24 ähnelt.
        /// </summary>
        public static string ExampleHostRange {
            get {
                return ResourceManager.GetString("ExampleHostRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die i-0b22a22eec53b9321 ähnelt.
        /// </summary>
        public static string ExampleInstanceId {
            get {
                return ResourceManager.GetString("ExampleInstanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.178.55 ähnelt.
        /// </summary>
        public static string ExampleIPv4Address {
            get {
                return ResourceManager.GetString("ExampleIPv4Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.178.255 ähnelt.
        /// </summary>
        public static string ExampleIPv4Broadcast {
            get {
                return ResourceManager.GetString("ExampleIPv4Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 8.8.8.8 ähnelt.
        /// </summary>
        public static string ExampleIPv4DNSServer {
            get {
                return ResourceManager.GetString("ExampleIPv4DNSServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.178.1; 8.8.8.8; 8.8.4.4 ähnelt.
        /// </summary>
        public static string ExampleIPv4DNSServers {
            get {
                return ResourceManager.GetString("ExampleIPv4DNSServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.178.1 ähnelt.
        /// </summary>
        public static string ExampleIPv4Gateway {
            get {
                return ResourceManager.GetString("ExampleIPv4Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.178.133/255.255.255.0 or 2001:0db8::/64 ähnelt.
        /// </summary>
        public static string ExampleIPv4IPv6Subnet {
            get {
                return ResourceManager.GetString("ExampleIPv4IPv6Subnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.178.134/255.255.255.0 or 2001:0db9::/64 ähnelt.
        /// </summary>
        public static string ExampleIPv4IPv6Subnet2 {
            get {
                return ResourceManager.GetString("ExampleIPv4IPv6Subnet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.180.0/24 or 2001:0db9::/54 ähnelt.
        /// </summary>
        public static string ExampleIPv4IPv6Subnet3 {
            get {
                return ResourceManager.GetString("ExampleIPv4IPv6Subnet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.178.0/24 or 192.168.178.0/255.255.255.0 ähnelt.
        /// </summary>
        public static string ExampleIPv4Subnet {
            get {
                return ResourceManager.GetString("ExampleIPv4Subnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.179.0/24 or 192.168.179.0/255.255.255.0 ähnelt.
        /// </summary>
        public static string ExampleIPv4Subnet2 {
            get {
                return ResourceManager.GetString("ExampleIPv4Subnet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 255.255.255.0 ähnelt.
        /// </summary>
        public static string ExampleIPv4Subnetmask {
            get {
                return ResourceManager.GetString("ExampleIPv4Subnetmask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /24 or 255.255.255.0 ähnelt.
        /// </summary>
        public static string ExampleIPv4SubnetmaskIPv4CIDR {
            get {
                return ResourceManager.GetString("ExampleIPv4SubnetmaskIPv4CIDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 255.255.255.0 or /64 ähnelt.
        /// </summary>
        public static string ExampleIPv4SubnetmaskIPv6CIDR {
            get {
                return ResourceManager.GetString("ExampleIPv4SubnetmaskIPv6CIDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 192.168.100.0/24 ähnelt.
        /// </summary>
        public static string ExampleIPv4SubnetWithCIDR {
            get {
                return ResourceManager.GetString("ExampleIPv4SubnetWithCIDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2606:4700:4700::1111 ähnelt.
        /// </summary>
        public static string ExampleIPv6Address {
            get {
                return ResourceManager.GetString("ExampleIPv6Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 00:F1:21:AB:0B:35 ähnelt.
        /// </summary>
        public static string ExampleMACAddress {
            get {
                return ResourceManager.GetString("ExampleMACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 01:23:45:67:89:AB; 01-23-45; AA11BB; 00F1A2C3D4E5; Intel Corp; Asus ähnelt.
        /// </summary>
        public static string ExampleMACAddressesOrVendor {
            get {
                return ResourceManager.GetString("ExampleMACAddressesOrVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 161 ähnelt.
        /// </summary>
        public static string ExamplePort161 {
            get {
                return ResourceManager.GetString("ExamplePort161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 22 ähnelt.
        /// </summary>
        public static string ExamplePort22 {
            get {
                return ResourceManager.GetString("ExamplePort22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 23 ähnelt.
        /// </summary>
        public static string ExamplePort23 {
            get {
                return ResourceManager.GetString("ExamplePort23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3389 ähnelt.
        /// </summary>
        public static string ExamplePort3389 {
            get {
                return ResourceManager.GetString("ExamplePort3389", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 513 ähnelt.
        /// </summary>
        public static string ExamplePort513 {
            get {
                return ResourceManager.GetString("ExamplePort513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 53 ähnelt.
        /// </summary>
        public static string ExamplePort53 {
            get {
                return ResourceManager.GetString("ExamplePort53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5900 ähnelt.
        /// </summary>
        public static string ExamplePort5900 {
            get {
                return ResourceManager.GetString("ExamplePort5900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 7 ähnelt.
        /// </summary>
        public static string ExamplePort7 {
            get {
                return ResourceManager.GetString("ExamplePort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 22; 80; https; ldaps; 777 - 999; 8080 ähnelt.
        /// </summary>
        public static string ExamplePortPortRangeOrService {
            get {
                return ResourceManager.GetString("ExamplePortPortRangeOrService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 22; 80; 443 ähnelt.
        /// </summary>
        public static string ExamplePorts {
            get {
                return ResourceManager.GetString("ExamplePorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 22; 80; 443; 500 - 999; 8080 ähnelt.
        /// </summary>
        public static string ExamplePortScanRange {
            get {
                return ResourceManager.GetString("ExamplePortScanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://api.ipify.org ähnelt.
        /// </summary>
        public static string ExamplePublicIPv4AddressAPI {
            get {
                return ResourceManager.GetString("ExamplePublicIPv4AddressAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://api6.ipify.org ähnelt.
        /// </summary>
        public static string ExamplePublicIPv6AddressAPI {
            get {
                return ResourceManager.GetString("ExamplePublicIPv6AddressAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Webserver ähnelt.
        /// </summary>
        public static string ExampleRemoteDesktopProfileName {
            get {
                return ResourceManager.GetString("ExampleRemoteDesktopProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COM5 ähnelt.
        /// </summary>
        public static string ExampleSerialLine {
            get {
                return ResourceManager.GetString("ExampleSerialLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die public ähnelt.
        /// </summary>
        public static string ExampleSNMPCommunity {
            get {
                return ResourceManager.GetString("ExampleSNMPCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.3.6.1.2.1.1 ähnelt.
        /// </summary>
        public static string ExampleSNMPOID {
            get {
                return ResourceManager.GetString("ExampleSNMPOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die snmp-user ähnelt.
        /// </summary>
        public static string ExampleSNMPUsername {
            get {
                return ResourceManager.GetString("ExampleSNMPUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die example.com ähnelt.
        /// </summary>
        public static string ExampleSuffix {
            get {
                return ResourceManager.GetString("ExampleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die server; dmz ähnelt.
        /// </summary>
        public static string ExampleTags {
            get {
                return ResourceManager.GetString("ExampleTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Admin ähnelt.
        /// </summary>
        public static string ExampleUsername {
            get {
                return ResourceManager.GetString("ExampleUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 80; 443; 8080; 8443 ähnelt.
        /// </summary>
        public static string ExampleWebserverPorts {
            get {
                return ResourceManager.GetString("ExampleWebserverPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http(s)://example.com/index.html ähnelt.
        /// </summary>
        public static string ExampleWebsiteUri {
            get {
                return ResourceManager.GetString("ExampleWebsiteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GitHub ähnelt.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die •••••••••••• ähnelt.
        /// </summary>
        public static string HiddenPassword {
            get {
                return ResourceManager.GetString("HiddenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iexplore.exe ähnelt.
        /// </summary>
        public static string IExploreExe {
            get {
                return ResourceManager.GetString("IExploreExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Internet Explorer ähnelt.
        /// </summary>
        public static string InternetExplorer {
            get {
                return ResourceManager.GetString("InternetExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JSON ähnelt.
        /// </summary>
        public static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C:\Data\Keys\private_ssh.ppk ähnelt.
        /// </summary>
        public static string PrivateKeyFileLocationDots {
            get {
                return ResourceManager.GetString("PrivateKeyFileLocationDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NETworkManager ähnelt.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TXT ähnelt.
        /// </summary>
        public static string TXT {
            get {
                return ResourceManager.GetString("TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML ähnelt.
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
