//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETworkManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETworkManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared Controlz for WPF and ... more. ähnelt.
        /// </summary>
        public static string Libary_ControlEx_Description {
            get {
                return ResourceManager.GetString("Libary_ControlEx_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/ControlzEx/ControlzEx/blob/master/LICENSE ähnelt.
        /// </summary>
        public static string Libary_ControlzEx_LicenseUrl {
            get {
                return ResourceManager.GetString("Libary_ControlzEx_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ControlzEx ähnelt.
        /// </summary>
        public static string Libary_ControlzEx_Name {
            get {
                return ResourceManager.GetString("Libary_ControlzEx_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/ControlzEx/ControlzEx ähnelt.
        /// </summary>
        public static string Libary_ControlzEx_ProjectUrl {
            get {
                return ResourceManager.GetString("Libary_ControlzEx_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dragable and tearable tab control for WPF. ähnelt.
        /// </summary>
        public static string Libary_Dragablz_Description {
            get {
                return ResourceManager.GetString("Libary_Dragablz_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/ButchersBoy/Dragablz/blob/master/LICENSE ähnelt.
        /// </summary>
        public static string Libary_Dragablz_LicenseUrl {
            get {
                return ResourceManager.GetString("Libary_Dragablz_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dragablz ähnelt.
        /// </summary>
        public static string Libary_Dragablz_Name {
            get {
                return ResourceManager.GetString("Libary_Dragablz_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/ButchersBoy/Dragablz ähnelt.
        /// </summary>
        public static string Libary_Dragablz_ProjectUrl {
            get {
                return ResourceManager.GetString("Libary_Dragablz_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reusable DNS resolver component. ähnelt.
        /// </summary>
        public static string Libary_HeijdenDNS_Description {
            get {
                return ResourceManager.GetString("Libary_HeijdenDNS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.codeproject.com/info/cpol10.aspx ähnelt.
        /// </summary>
        public static string Libary_HeijdenDNS_LicenseUrl {
            get {
                return ResourceManager.GetString("Libary_HeijdenDNS_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heijden.DNS ähnelt.
        /// </summary>
        public static string Libary_HeijdenDNS_Name {
            get {
                return ResourceManager.GetString("Libary_HeijdenDNS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.codeproject.com/Articles/23673/DNS-NET-Resolver-C ähnelt.
        /// </summary>
        public static string Libary_HeijdenDNS_ProjectUrl {
            get {
                return ResourceManager.GetString("Libary_HeijdenDNS_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some awesome icons for WPF and UWP all together... ähnelt.
        /// </summary>
        public static string Libary_MahAppsMetroIconPacks_Description {
            get {
                return ResourceManager.GetString("Libary_MahAppsMetroIconPacks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/MahApps/MahApps.Metro.IconPacks/blob/master/LICENSE ähnelt.
        /// </summary>
        public static string Libary_MahAppsMetroIconPacks_LicenseUrl {
            get {
                return ResourceManager.GetString("Libary_MahAppsMetroIconPacks_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MahApps.Metro.IconPacks ähnelt.
        /// </summary>
        public static string Libary_MahAppsMetroIconPacks_Name {
            get {
                return ResourceManager.GetString("Libary_MahAppsMetroIconPacks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/MahApps/MahApps.Metro.IconPacks ähnelt.
        /// </summary>
        public static string Libary_MahAppsMetroIconPacks_ProjectUrl {
            get {
                return ResourceManager.GetString("Libary_MahAppsMetroIconPacks_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A GitHub API client library for .NET ähnelt.
        /// </summary>
        public static string Libary_Octokit_Description {
            get {
                return ResourceManager.GetString("Libary_Octokit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/octokit/octokit.net/blob/master/LICENSE.txt ähnelt.
        /// </summary>
        public static string Libary_Octokit_LicenseURL {
            get {
                return ResourceManager.GetString("Libary_Octokit_LicenseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Octokit ähnelt.
        /// </summary>
        public static string Libary_Octokit_Name {
            get {
                return ResourceManager.GetString("Libary_Octokit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/octokit/octokit.net ähnelt.
        /// </summary>
        public static string Libary_Octokit_ProjectURL {
            get {
                return ResourceManager.GetString("Libary_Octokit_ProjectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sharp SNMP Library- Open Source SNMP for .NET and Mono ähnelt.
        /// </summary>
        public static string Libary_SharpSNMPLib_Description {
            get {
                return ResourceManager.GetString("Libary_SharpSNMPLib_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/lextm/sharpsnmplib/blob/master/LICENSE ähnelt.
        /// </summary>
        public static string Libary_SharpSNMPLib_LicenseUrl {
            get {
                return ResourceManager.GetString("Libary_SharpSNMPLib_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #SNMP Libary ähnelt.
        /// </summary>
        public static string Libary_SharpSNMPLib_Name {
            get {
                return ResourceManager.GetString("Libary_SharpSNMPLib_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/lextm/sharpsnmplib ähnelt.
        /// </summary>
        public static string Libary_SharpSNMPLib_ProjectUrl {
            get {
                return ResourceManager.GetString("Libary_SharpSNMPLib_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code Project Open License ähnelt.
        /// </summary>
        public static string License_CPOL {
            get {
                return ResourceManager.GetString("License_CPOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GNU General Public License v3.0 ähnelt.
        /// </summary>
        public static string License_GNUGPLv3 {
            get {
                return ResourceManager.GetString("License_GNUGPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MIT License ähnelt.
        /// </summary>
        public static string License_MIT {
            get {
                return ResourceManager.GetString("License_MIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NETworkManager ähnelt.
        /// </summary>
        public static string NETworkManager_GitHub_Repo {
            get {
                return ResourceManager.GetString("NETworkManager_GitHub_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BornToBeRoot ähnelt.
        /// </summary>
        public static string NETworkManager_GitHub_User {
            get {
                return ResourceManager.GetString("NETworkManager_GitHub_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/BornToBeRoot/NETworkManager/releases/latest ähnelt.
        /// </summary>
        public static string NETworkManager_LatestReleaseURL {
            get {
                return ResourceManager.GetString("NETworkManager_LatestReleaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/BornToBeRoot/NETworkManager/blob/master/LICENSE ähnelt.
        /// </summary>
        public static string NETworkManager_LicenseUrl {
            get {
                return ResourceManager.GetString("NETworkManager_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NETworkManager ähnelt.
        /// </summary>
        public static string NETworkManager_ProjectName {
            get {
                return ResourceManager.GetString("NETworkManager_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://github.com/BornToBeRoot/NETworkManager ähnelt.
        /// </summary>
        public static string NETworkManager_ProjectUrl {
            get {
                return ResourceManager.GetString("NETworkManager_ProjectUrl", resourceCulture);
            }
        }
    }
}
