namespace NETworkManager.Models.Documentation
{    public enum DocumentationIdentifier
    {
        Default,
        ApplicationDashboard,
        ApplicationNetworkInterface,
        ApplicationWiFi,
        ApplicationIPScanner,
        ApplicationPortScanner,
        ApplicationPing,
        ApplicationPingMonitor,
        ApplicationTraceroute,
        ApplicationDnsLookup,
        ApplicationRemoteDesktop,
        ApplicationPowerShell,
        ApplicationPutty,
        ApplicationTigerVNC,
        ApplicationWebConsole,
        ApplicationSnmp,
        ApplicationDiscoveryProtocol,
        ApplicationWakeOnLan,
        ApplicationHttpHeaders,
        ApplicationWhois,
        ApplicationSubnetCalculator,
        ApplicationLookup,
        ApplicationConnections,
        ApplicationListeners,
        ApplicationArpTable
    }
}
