namespace NETworkManager.Settings
{
    public enum SettingsViewName
    {
        General,
        Window,
        Appearance,
        Language,
        Status,
        HotKeys,
        Autostart,
        Update,        
        Profiles,
        Settings,
        Dashboard,
        IPScanner,
        PortScanner,
        PingMonitor,
        Traceroute,
        DNSLookup,
        RemoteDesktop,
        PowerShell,
        PuTTY,
        TigerVNC,
        SNMP,
        WakeOnLAN,
        Whois
    }
}
