//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETworkManager.Settings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETworkManager.Settings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://mahapps.com/.
        /// </summary>
        public static string Libary_MahAppsMetro_Url {
            get {
                return ResourceManager.GetString("Libary_MahAppsMetro_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/MahApps/MahApps.Metro.IconPacks.
        /// </summary>
        public static string Libary_MahAppsMetroIconPacks_Url {
            get {
                return ResourceManager.GetString("Libary_MahAppsMetroIconPacks_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string Localization_DefaultCultureCode {
            get {
                return ResourceManager.GetString("Localization_DefaultCultureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkInterfaceConfigTemplates.xml.
        /// </summary>
        public static string NetworkInterface_ConfigTemplates_FileName {
            get {
                return ResourceManager.GetString("NetworkInterface_ConfigTemplates_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/BornToBeRoot/NETworkManager.
        /// </summary>
        public static string Project_GitHub_Url {
            get {
                return ResourceManager.GetString("Project_GitHub_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string StartParameter_Autostart {
            get {
                return ResourceManager.GetString("StartParameter_Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string WakeOnLan_DefaultPort {
            get {
                return ResourceManager.GetString("WakeOnLan_DefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WakeOnLanTemplates.xml.
        /// </summary>
        public static string WakeOnLan_Templates_FileName {
            get {
                return ResourceManager.GetString("WakeOnLan_Templates_FileName", resourceCulture);
            }
        }
    }
}
