//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETworkManager.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NETworkManager.Resources.Localization.StaticStrings", typeof(StaticStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9600.
        /// </summary>
        public static string ExampleBaud9600 {
            get {
                return ResourceManager.GetString("ExampleBaud9600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-Testuser.
        /// </summary>
        public static string ExampleCredentialName {
            get {
                return ResourceManager.GetString("ExampleCredentialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example.com.
        /// </summary>
        public static string ExampleDomain {
            get {
                return ResourceManager.GetString("ExampleDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string ExampleGroupServers {
            get {
                return ResourceManager.GetString("ExampleGroupServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switche.
        /// </summary>
        public static string ExampleGroupSwitche {
            get {
                return ResourceManager.GetString("ExampleGroupSwitche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER-01.
        /// </summary>
        public static string ExampleHostname {
            get {
                return ResourceManager.GetString("ExampleHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.178.1; example.com.
        /// </summary>
        public static string ExampleHostnameAndOrIPAddress {
            get {
                return ResourceManager.GetString("ExampleHostnameAndOrIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER-01 or 172.16.0.100.
        /// </summary>
        public static string ExampleHostnameOrIPAddress {
            get {
                return ResourceManager.GetString("ExampleHostnameOrIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.1.0/24; 192.168.178.1 - 192.168.178.128; 192.168.[178-179].[1,100,150-200]; example.com/24.
        /// </summary>
        public static string ExampleHostRange {
            get {
                return ResourceManager.GetString("ExampleHostRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.178.55.
        /// </summary>
        public static string ExampleIPv4Address {
            get {
                return ResourceManager.GetString("ExampleIPv4Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.178.255.
        /// </summary>
        public static string ExampleIPv4Broadcast {
            get {
                return ResourceManager.GetString("ExampleIPv4Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.8.8.8.
        /// </summary>
        public static string ExampleIPv4DNSServer {
            get {
                return ResourceManager.GetString("ExampleIPv4DNSServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.178.1; 8.8.8.8; 8.8.4.4.
        /// </summary>
        public static string ExampleIPv4DNSServers {
            get {
                return ResourceManager.GetString("ExampleIPv4DNSServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.178.1.
        /// </summary>
        public static string ExampleIPv4Gateway {
            get {
                return ResourceManager.GetString("ExampleIPv4Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.178.133/255.255.255.0 or 2001:0db8::/64.
        /// </summary>
        public static string ExampleIPv4IPv6Subnet {
            get {
                return ResourceManager.GetString("ExampleIPv4IPv6Subnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.178.134/255.255.255.0 or 2001:0db9::/64.
        /// </summary>
        public static string ExampleIPv4IPv6Subnet2 {
            get {
                return ResourceManager.GetString("ExampleIPv4IPv6Subnet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.180.0/24 or 2001:0db9::/54.
        /// </summary>
        public static string ExampleIPv4IPv6Subnet3 {
            get {
                return ResourceManager.GetString("ExampleIPv4IPv6Subnet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.178.0/24 or 192.168.178.0/255.255.255.0.
        /// </summary>
        public static string ExampleIPv4Subnet {
            get {
                return ResourceManager.GetString("ExampleIPv4Subnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.179.0/24 or 192.168.179.0/255.255.255.0.
        /// </summary>
        public static string ExampleIPv4Subnet2 {
            get {
                return ResourceManager.GetString("ExampleIPv4Subnet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255.255.255.0.
        /// </summary>
        public static string ExampleIPv4Subnetmask {
            get {
                return ResourceManager.GetString("ExampleIPv4Subnetmask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /24 or 255.255.255.0.
        /// </summary>
        public static string ExampleIPv4SubnetmaskIPv4CIDR {
            get {
                return ResourceManager.GetString("ExampleIPv4SubnetmaskIPv4CIDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255.255.255.0 or /64.
        /// </summary>
        public static string ExampleIPv4SubnetmaskIPv6CIDR {
            get {
                return ResourceManager.GetString("ExampleIPv4SubnetmaskIPv6CIDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.100.0/24.
        /// </summary>
        public static string ExampleIPv4SubnetWithCIDR {
            get {
                return ResourceManager.GetString("ExampleIPv4SubnetWithCIDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:F1:21:AB:0B:35.
        /// </summary>
        public static string ExampleMACAddress {
            get {
                return ResourceManager.GetString("ExampleMACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01:23:45:67:89:AB; 01-23-45; AA11BB; 00F1A2C3D4E5; Intel Corp; Asus.
        /// </summary>
        public static string ExampleMACAddressesOrVendor {
            get {
                return ResourceManager.GetString("ExampleMACAddressesOrVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 161.
        /// </summary>
        public static string ExamplePort161 {
            get {
                return ResourceManager.GetString("ExamplePort161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string ExamplePort22 {
            get {
                return ResourceManager.GetString("ExamplePort22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string ExamplePort23 {
            get {
                return ResourceManager.GetString("ExamplePort23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3389.
        /// </summary>
        public static string ExamplePort3389 {
            get {
                return ResourceManager.GetString("ExamplePort3389", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 513.
        /// </summary>
        public static string ExamplePort513 {
            get {
                return ResourceManager.GetString("ExamplePort513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53.
        /// </summary>
        public static string ExamplePort53 {
            get {
                return ResourceManager.GetString("ExamplePort53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5900.
        /// </summary>
        public static string ExamplePort5900 {
            get {
                return ResourceManager.GetString("ExamplePort5900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string ExamplePort7 {
            get {
                return ResourceManager.GetString("ExamplePort7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22; 80; https; ldaps; 777 - 999; 8080.
        /// </summary>
        public static string ExamplePortPortRangeOrService {
            get {
                return ResourceManager.GetString("ExamplePortPortRangeOrService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22; 80; 443; 500 - 999; 8080.
        /// </summary>
        public static string ExamplePortScanRange {
            get {
                return ResourceManager.GetString("ExamplePortScanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.ipify.org.
        /// </summary>
        public static string ExamplePublicIPAddressAPI {
            get {
                return ResourceManager.GetString("ExamplePublicIPAddressAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webserver.
        /// </summary>
        public static string ExampleRemoteDesktopProfileName {
            get {
                return ResourceManager.GetString("ExampleRemoteDesktopProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM5.
        /// </summary>
        public static string ExampleSerialLine {
            get {
                return ResourceManager.GetString("ExampleSerialLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        public static string ExampleSNMPCommunity {
            get {
                return ResourceManager.GetString("ExampleSNMPCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.3.6.1.2.1.1.
        /// </summary>
        public static string ExampleSNMPOID {
            get {
                return ResourceManager.GetString("ExampleSNMPOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snmp-user.
        /// </summary>
        public static string ExampleSNMPUsername {
            get {
                return ResourceManager.GetString("ExampleSNMPUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example.com.
        /// </summary>
        public static string ExampleSuffix {
            get {
                return ResourceManager.GetString("ExampleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server; dmz.
        /// </summary>
        public static string ExampleTags {
            get {
                return ResourceManager.GetString("ExampleTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ExampleUsername {
            get {
                return ResourceManager.GetString("ExampleUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80; 443; 8080; 8443.
        /// </summary>
        public static string ExampleWebserverPorts {
            get {
                return ResourceManager.GetString("ExampleWebserverPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http(s)://example.com/index.html.
        /// </summary>
        public static string ExampleWebsiteUri {
            get {
                return ResourceManager.GetString("ExampleWebsiteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ••••••••••••.
        /// </summary>
        public static string HiddenPassword {
            get {
                return ResourceManager.GetString("HiddenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETworkManager.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TXT.
        /// </summary>
        public static string TXT {
            get {
                return ResourceManager.GetString("TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
